name: Generate repository list

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *' # Every hour
  
jobs:
  repo-list:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Get the repos
      uses: helaili/ea-repo-list@master
      with:
        enterprise: andrekolodochka
        outputFilename: repositories.json
        token: ${{secrets.GH_EA_TOKEN}}
    - name: filter for org
      uses: actions/github-script@v4
      with: 
        script: |
          var json = require('./repositories.json'); 
          console.log(json)
          console.log(JSON.parse(json))
        
    - name: Save the repos
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "latest list of repos"
          git push
