name: Generate repository list

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *' # Every hour
  
jobs:
  repo-list:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: get repos
      uses: actions/github-script@v4
      with: 
        github-token: ${{secrets.GH_EA_TOKEN}}
        script: |
          let repoResult = []
          await github.paginate(github.repos.listForOrg, {
            org: "octo-faq", 
          }).then(repos => {
            for(let repo of repos) {
              let {name, full_name, description, html_url, language, stargazers_count, watchers_count, forks_count, topics} = repo
              repoResult.push({name, full_name, description, html_url, language, stargazers_count, watchers_count, forks_count, topics})
            }
          })
          console.log(repoResult)
          fs.writeFileSync('repositories.json', JSON.stringify(repoResult))
        
    - name: Save the repos
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "latest list of repos"
          git push
